name: Block Specific PR

on:
  pull_request:
    branches:
      - master

jobs:
  block_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          if [[ "$PR_TITLE" == *"DO NOT MERGE"* ]]; then
            echo "Blocking PR merge"
            exit 1  
          fi
